---
services:
  gluetun-books:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun-books
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - UPDATER_PERIOD=24h
      - VPN_PORT_FORWARDING=${VPN_PORT_FORWARDING}
      - VPN_PORT_FORWARDING_PROVIDER=${VPN_PORT_FORWARDING_PROVIDER}
      - VPN_PORT_FORWARDING_LISTENING_PORT=${VPN_PORT_FORWARDING_LISTENING_PORT}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - HTTP_CONTROL_SERVER_LOG=on
    volumes:
      - /DATA/AppData/Gluetun-books:/gluetun
    restart: unless-stopped
    privileged: false
    ports:
      - "8084:8084"   # qBittorrent Web UI
      - "29500:29500"   # Torrenting
      - "29500:29500/udp"
      - "8003:8000"

  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /DATA/AppData/readarr:/config
      - /DATA/Media/AudioBooks:/data/audiobooks
    ports:
      - 8787:8787
    restart: unless-stopped

  prowlarr-books:
    image: lscr.io/linuxserver/prowlarr:1.33.3
    container_name: prowlarr-books
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /DATA/AppData/prowlarr-books/config:/config
      - /DATA/Downloads:/data/downloads
      - /DATA/AppData/prowlarr-books/backup:/data/backup
    ports:
      - "9697:9696"
    restart: unless-stopped

  qbittorrent-books:
    image: lscr.io/linuxserver/qbittorrent:5.0.1
    container_name: qbittorrent-books
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - /DATA/AppData/qbittorrent-books/config:/config
      - /DATA/AppData/qbittorrent-books/downloads:/data/downloads
      - /DATA/Media/AudioBooks:/data/audiobooks
    depends_on:
      - gluetun-books
    network_mode: "service:gluetun-books"
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.20.0
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /DATA/Media/AudioBooks:/audiobooks
      - /DATA/Media/Podcasts:/podcasts
      - /DATA/AppData/audiobookshelf/config:/config
      - /DATA/AppData/audiobookshelf/metadata:/metadata
    environment:
      - TZ=${TZ}
