---
services:
  gluetun-books:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun-books
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - UPDATER_PERIOD=24h
      - VPN_PORT_FORWARDING=${VPN_PORT_FORWARDING}
      - VPN_PORT_FORWARDING_PROVIDER=${VPN_PORT_FORWARDING_PROVIDER}
      - VPN_PORT_FORWARDING_LISTENING_PORT=${VPN_PORT_FORWARDING_LISTENING_PORT}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - HTTP_CONTROL_SERVER_LOG=on
    volumes:
      - /DATA/AppData/Gluetun-books:/gluetun
    ports:
      - "8084:8084"      # qBittorrent Web UI
      - "29500:29500"    # Torrenting (TCP)
      - "29500:29500/udp"
      - "8003:8000"      # Optional Gluetun control
    restart: unless-stopped
    privileged: false

  qbittorrent-books:
    image: lscr.io/linuxserver/qbittorrent:5.0.1
    container_name: qbittorrent-books
    network_mode: "service:gluetun-books"
    depends_on:
      - gluetun-books
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8084
    volumes:
      - /DATA/AppData/qbittorrent-books/config:/config
      - /DATA/AppData/qbittorrent-books/downloads:/data/downloads
      - /DATA/Media/AudioBooks:/data/audiobooks
    restart: unless-stopped

  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:version-d3ebf0b6
    container_name: lazylibrarian
    ports:
      - 5299:5299
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /DATA/AppData/lazylibrarian:/config
      - /DATA/AppData/qbittorrent-books/downloads:/data/downloads
      - /DATA/Media/AudioBooks:/data/audiobooks
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:v0.21.2142
    container_name: jackett
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /DATA/AppData/jackett:/config
      - /DATA/AppData/qbittorrent-books/downlogit ads:/data/downloads
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.20.0
    container_name: audiobookshelf
    ports:
      - 13378:80
    environment:
      - TZ=${TZ}
    volumes:
      - /DATA/Media/AudioBooks:/audiobooks
      - /DATA/Media/Podcasts:/podcasts
      - /DATA/AppData/audiobookshelf/config:/config
      - /DATA/AppData/audiobookshelf/metadata:/metadata
    restart: unless-stopped
