---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.0.4
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /DATA/AppData/homepage/config:/app/config
      - /DATA/AppData/homepage/images:/app/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
    restart: unless-stopped
