---
services:
  gluetun:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - UPDATER_PERIOD=24h
      - SERVER_REGIONS=Netherlands
      - HTTP_CONTROL_SERVER_LOG=on
    volumes:
      - /DATA/AppData/Gluetun:/gluetun
    restart: unless-stopped
    privileged: false
    ports:
      - "8080:8080"   # qBittorrent Web UI
      - "8097:8096"   # Jellyfin Web UI
      - "6881:6881"   # Torrenting
      - "6881:6881/udp"
      - "8002:8000"

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.14
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /DATA/AppData/sonarr/config:/config
      - /DATA/Media/Shows:/data/tv
      - /DATA/Downloads:/data/downloads
    ports:
      - "8989:8989"   # Sonarr Web UI
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:5.20.2
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /DATA/AppData/radarr/config:/config
      - /DATA/Media/Movies:/data/movies
      - /DATA/Downloads:/data/downloads
    ports:
      - "7878:7878"   # Radarr Web UI
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.32.2
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /DATA/AppData/prowlarr/config:/config
      - /DATA/Downloads:/data/downloads
      - /DATA/AppData/prowlarr/backup:/data/backup
    ports:
      - "9696:9696"  # Prowlarr Web UI
    depends_on:
      - gluetun
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.0.1
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - /DATA/AppData/qbittorrent/config:/config
      - /DATA/Downloads:/data/downloads
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:10.10.6
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /DATA/AppData/jellyfin/config:/config
      - /DATA/Media:/Media
      - /opt/vc/lib:/opt/vc/lib
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:2.5.1
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - TZ=${TZ}
    volumes:
      - /DATA/AppData/jellyseerr/config:/app/config
    ports:
      - "5055:5055"   # Jellyseerr Web UI
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:1.5.1
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /DATA/AppData/bazarr/config:/config
      - /DATA/Media/Movies:/data/movies
      - /DATA/Media/Shows:/data/tv
    ports:
      - "6767:6767"   # Bazarr Web UI
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr:v3.3.21
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    ports:
      - "8191:8191"   # FlareSolverr Web UI
    restart: unless-stopped
