version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/portainer/mediarr"
      - "/portainer/npm"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker-compose"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
