---
version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/portainer/*"
    schedule:
      interval: "daily"
    labels:
      - "enhancement"
      - "docker-compose"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"