---
version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/portainer"
    schedule:
      interval: "weekly"
    labels:
      - "enhancement"
      - "docker-compose"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "enhancement"
      - "github-action"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
