---
services:
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "9090:9090"
    environment:
      - UPTIME_KUMA_HOST=${UPTIME_KUMA_HOST}
      - UPTIME_KUMA_PORT=${UPTIME_KUMA_PORT}
      - UPTIME_KUMA_USER=${UPTIME_KUMA_USER}
      - UPTIME_KUMA_PASS=${UPTIME_KUMA_PASS}
    volumes:
      - "/DATA/AppData/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "/DATA/AppData/prometheus/data:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - TZ=${TZ}
    volumes:
      - "/DATA/AppData/grafana/data:/var/lib/grafana"
    depends_on:
      - prometheus
