global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Uptime Kuma
  - job_name: "uptime_kuma"
    basic_auth:
      username: someuser
      password: somepassword
    static_configs:
      - targets:
        - "x.x.x.x:0000"