---
services:

  invoiceshelf:
    container_name: invoiceshelf
    image: invoiceshelf/invoiceshelf:2.1.1
    restart: unless-stopped
    ports:
      - 90:80
    environment:
      - PHP_TZ=America/Toronto
      - TIMEZONE=America/Toronto
      - APP_NAME=Laravel
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://invoice.kamalchafik.ca
      - DB_CONNECTION=pgsql
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost:90
      - STARTUP_DELAY=10
    volumes:
      - /DATA/AppData/invoiceshelf/data:/data
      - /DATA/AppData/invoiceshelf/conf:/conf
