---
services:

  invoiceshelf:
    container_name: invoiceshelf
    image: invoiceshelf/invoiceshelf:2.1.1
    restart: unless-stopped
    ports:
      - 90:80
    environment:
      - PHP_TZ=America/Toronto
      - TIMEZONE=America/Toronto
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=https://invoice.kamalchafik.ca
      - DB_CONNECTION=pgsql
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=240
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=https://invoice.kamalchafik.ca
      - SANCTUM_STATEFUL_DOMAINS=invoice.kamalchafik.ca
      - SESSION_SECURE_COOKIE=true
      - STARTUP_DELAY=5
      - TRUSTED_PROXIES="*"
    volumes:
      - /DATA/AppData/invoiceshelf/data:/data
      - /DATA/AppData/invoiceshelf/conf:/conf
