---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
- Servers:
    - Polo:
        icon: proxmox.png
        href: http://{{POLO_VAR_IP}}:8006
        description: Monitoring
        siteMonitor: http://{{POLO_VAR_IP}}:8006
        widgets:
          - type: proxmox
            url: http://{{POLO_VAR_IP}}:8006

- Monitoring:
    - Uptime-Kuma:
        icon: https://static-00.iconduck.com/assets.00/uptime-kuma-icon-1024x940-gabwl61r.png
        href: http://{{HOMEPAGE_VAR_IP}}:3001
        description: Monitoring
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:3001
        widgets:
          - type: uptimekuma
            url: http://{{HOMEPAGE_VAR_IP}}:3001
            slug: homepage

    - Grafana:
        icon: grafana.png
        href: http://{{HOMEPAGE_VAR_IP}}:3003
        description: Metrics & Dashboards
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:3003
        widgets:
          - type: grafana
            url: http://{{HOMEPAGE_VAR_IP}}:3003
            username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
            password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}

    - Prometheus:
        icon: prometheus.png
        href: http://{{HOMEPAGE_VAR_IP}}:9090
        description: Metrics Collection
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:9090
        widget:
            type: prometheus
            url: http://{{HOMEPAGE_VAR_IP}}:9090

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://{{HOMEPAGE_VAR_IP}}:8097
        description: Media Server
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8097
        widgets:
          - type: jellyfin
            url: http://{{HOMEPAGE_VAR_IP}}:8097
            key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}

    - Jellyseerr:
        icon: jellyseerr.png
        href: http://{{HOMEPAGE_VAR_IP}}:5055
        description: Media Requests
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:5055
        widgets:
          - type: jellyseerr
            url: http://{{HOMEPAGE_VAR_IP}}:5055
            key: {{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}

    - Gluetun:
        href: http://{{HOMEPAGE_VAR_IP}}:8002
        description: Gluetun - VPN Container
        icon: gluetun.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8002
        widget:
            type: gluetun
            url: http://{{HOMEPAGE_VAR_IP}}:8002

    - Radarr:
        icon: radarr.png
        href: http://{{HOMEPAGE_VAR_IP}}:7878
        description: Movie Management
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:7878
        widgets:
          - type: radarr
            url: http://{{HOMEPAGE_VAR_IP}}:7878
            key: {{HOMEPAGE_VAR_RADARR_API_KEY}}

    - Sonarr:
        icon: sonarr.png
        href: http://{{HOMEPAGE_VAR_IP}}:8989
        description: TV Show Management
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8989
        widgets:
          - type: sonarr
            url: http://{{HOMEPAGE_VAR_IP}}:8989
            key: {{HOMEPAGE_VAR_SONARR_API_KEY}}

    - qBittorrent:
        icon: qbittorrent.png
        href: http://{{HOMEPAGE_VAR_IP}}:8080
        description: Torrent Client
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8080
        widgets:
          - type: qbittorrent
            url: http://{{HOMEPAGE_VAR_IP}}:8080
            username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
            password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎

- Mediarr:
    - Jellyfin:
        href: http://{{HOMEPAGE_VAR_IP}}:8097
        description: Jellyfin - Media Server
        icon: jellyfin.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8097

    - Jellyseerr:
        href: http://{{HOMEPAGE_VAR_IP}}:5055
        description: Jellyseerr - Media Requests
        icon: jellyseerr.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:5055

    - Sonarr:
        href: http://{{HOMEPAGE_VAR_IP}}:8989
        description: Sonarr - TV Show Management
        icon: sonarr.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8989

    - Radarr:
        href: http://{{HOMEPAGE_VAR_IP}}:7878
        description: Radarr - Movie Management
        icon: radarr.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:7878

    - Prowlarr:
        href: http://{{HOMEPAGE_VAR_IP}}:9696
        description: Prowlarr - Indexer Management
        icon: prowlarr.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:9696

    - qBittorrent:
        href: http://{{HOMEPAGE_VAR_IP}}:8080
        description: qBittorrent - Torrent Client
        icon: qbittorrent.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8080

    - Bazarr:
        href: http://{{HOMEPAGE_VAR_IP}}:6767
        description: Bazarr - Subtitle Management
        icon: bazarr.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:6767

    - FlareSolverr:
        href: http://{{HOMEPAGE_VAR_IP}}:8191
        description: FlareSolverr - Captcha Solver
        icon: flaresolverr.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8191

    - Gluetun:
        href: http://{{HOMEPAGE_VAR_IP}}:8002
        description: Gluetun - VPN Container
        icon: gluetun.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8002
