---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
- Servers:
    - Marco:
        icon: truenas.png
        href: https://{{HOMEPAGE_VAR_IP}}
        description: TrueNAS Server (coming soon)

    - Polo:
        icon: proxmox.png
        href: https://{{HOMEPAGE_VAR_POLO_IP}}:8006
        description: Proxmox Server 1
        siteMonitor: https://{{HOMEPAGE_VAR_POLO_IP}}:8006
        widgets:
          - type: proxmox
            url: https://{{HOMEPAGE_VAR_POLO_IP}}:8006
            username: {{HOMEPAGE_VAR_PROXMOX_API_ID}}
            password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}

    - Toto:
        icon: proxmox.png
        href: https://{{HOMEPAGE_VAR_POLO_IP}}:8006
        description: Proxmox Server 2 (coming soon)
        siteMonitor: https://{{HOMEPAGE_VAR_POLO_IP}}:8006

- Monitoring:
    - Uptime Kuma:
        icon: https://static-00.iconduck.com/assets.00/uptime-kuma-icon-1024x940-gabwl61r.png
        href: http://{{HOMEPAGE_VAR_IP}}:3001
        description: Uptime Monitoring
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:3001
        widgets:
          - type: uptimekuma
            url: http://{{HOMEPAGE_VAR_IP}}:3001
            slug: homepage

    - Grafana:
        icon: grafana.png
        href: http://{{HOMEPAGE_VAR_IP}}:3003
        description: Metrics & Dashboards
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:3003
        widgets:
          - type: grafana
            url: http://{{HOMEPAGE_VAR_IP}}:3003
            username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
            password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
            fields: ["datasources", "totalalerts", "alertstriggered"]

    - Prometheus:
        icon: prometheus.png
        href: http://{{HOMEPAGE_VAR_IP}}:9090
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:9090
        widgets:
          - type: prometheus
            url: http://{{HOMEPAGE_VAR_IP}}:9090

- Infra:
    - Portainer:
        icon: portainer.png
        href: https://{{HOMEPAGE_VAR_IP}}:9443
        description: Container manager
        siteMonitor: https://{{HOMEPAGE_VAR_IP}}:9443
        widgets:
          - type: portainer
            url: https://{{HOMEPAGE_VAR_IP}}:9443
            env: 3
            key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}

    - Home Assistant:
        icon: home-assistant.png
        href: http://{{HOMEPAGE_VAR_IP}}:8123
        description: Home automation
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8123
        widgets:
          - type: homeassistant
            url: http://{{HOMEPAGE_VAR_IP}}:8123
            key: {{HOMEPAGE_VAR_HA_API_KEY}}

    - Semaphore UI:
        icon: semaphore.png
        href: http://{{HOMEPAGE_VAR_IP}}:3030
        description: Ansible and OpenTofu UI
        server: marco
        container: semaphore

- Databases:
    - phpMyAdmin:
        icon: phpmyadmin.png
        href: http://{{HOMEPAGE_VAR_IP}}:8082
        description: UI for MySQL
        server: marco
        container: mysql-phpmyadmin-1

    - MySQL:
        icon: mysql.png
        description: MySQL Database
        server: marco
        container: mysql-mysql-1

- Mediarr:
    - Jellyfin:
        icon: jellyfin.png
        href: http://{{HOMEPAGE_VAR_IP}}:8097
        description: Media Server
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8097
        widgets:
          - type: jellyfin
            url: http://{{HOMEPAGE_VAR_IP}}:8097
            key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
            enableBlocks: true
            enableNowPlaying: true
            enableUser: true
            showEpisodeNumber: true
            expandOneStreamToTwoRows: false
            fields: ["movies", "series", "episodes"]

    - Jellyseerr:
        icon: jellyseerr.png
        href: http://{{HOMEPAGE_VAR_IP}}:5055
        description: Media Requests
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:5055
        widgets:
          - type: jellyseerr
            url: http://{{HOMEPAGE_VAR_IP}}:5055
            key: {{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}

    - Gluetun:
        href: http://{{HOMEPAGE_VAR_IP}}:8002
        description: VPN Container
        icon: gluetun.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8002
        widgets:
          - type: gluetun
            url: http://{{HOMEPAGE_VAR_IP}}:8002

    - Radarr:
        icon: radarr.png
        href: http://{{HOMEPAGE_VAR_IP}}:7878
        description: Movie Management
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:7878
        widgets:
          - type: radarr
            url: http://{{HOMEPAGE_VAR_IP}}:7878
            key: {{HOMEPAGE_VAR_RADARR_API_KEY}}

    - Sonarr:
        icon: sonarr.png
        href: http://{{HOMEPAGE_VAR_IP}}:8989
        description: TV Show Management
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8989
        widgets:
          - type: sonarr
            url: http://{{HOMEPAGE_VAR_IP}}:8989
            key: {{HOMEPAGE_VAR_SONARR_API_KEY}}

    - qBittorrent:
        icon: qbittorrent.png
        href: http://{{HOMEPAGE_VAR_IP}}:8080
        description: Torrent Client
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8080
        widgets:
          - type: qbittorrent
            url: http://{{HOMEPAGE_VAR_IP}}:8080
            username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
            password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}

    - Prowlarr:
        href: http://{{HOMEPAGE_VAR_IP}}:9696
        description: Indexer
        icon: prowlarr.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:9696
        widgets:
          - type: prowlarr
            url: http://{{HOMEPAGE_VAR_IP}}:9696
            key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}

    - Bazarr:
        href: http://{{HOMEPAGE_VAR_IP}}:6767
        description: Subtitle Management
        icon: bazarr.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:6767
        widgets:
          - type: bazarr
            url: http://{{HOMEPAGE_VAR_IP}}:6767
            key: {{HOMEPAGE_VAR_BAZARR_API_KEY}}

- AI:
    - Ollama:
        icon: ollama.png
        href: http://{{HOMEPAGE_VAR_IP}}:11434
        description: Ollama
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:11434

    - Open Web UI:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/open-webui.png
        href: http://{{HOMEPAGE_VAR_IP}}:8081
        description: UI for AI
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8081

- Utilities:
    - Vaultwarden:
        icon: vaultwarden.png
        href: http://{{HOMEPAGE_VAR_IP}}:10380
        description: Password Manager
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:10380

    - Duplicati:
        icon: duplicati.png
        href: http://{{HOMEPAGE_VAR_IP}}:8200
        description: Backup Service
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8200

    - FlareSolverr:
        href: http://{{HOMEPAGE_VAR_IP}}:8191
        description: Captcha Solver
        icon: flaresolverr.png
        siteMonitor: http://{{HOMEPAGE_VAR_IP}}:8191
