---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
showStats: true
statusStyle: "dot"

background:
  image: /images/landscape-tree.jpg
  blur: sm
  saturate: 30
  brightness: 80
  opacity: 30

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Servers:
    style: row
    columns: 2
  Infra:
    style: row
    columns: 4
  Monitoring:
    style: row
    columns: 3
  Mediarr:
    style: row
    columns: 4
