---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/
- search:
    provider: [duckduckgo, google]
    showSearchSuggestions: true
    target: _blank

- datetime:
    text_size: xl
    format:
      timeStyle: short

- openmeteo:
    label: Montreal
    latitude: 45.552691929431404
    longitude: -73.66655474509646
    timezone: America/Toronto
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 0

- resources:
    label: Storage
    disk: /data
    expanded: true

- resources:
    label: System
    cpu: true
    memory: true
    cputemp: true
    tempmin: 0
    tempmax: 100

- resources:
    label: Up time
    uptime: true
