---
services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:2025.4.0
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - /DATA/AppData/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
