---
services:
  semaphore:
    container_name: semaphore
    image: docker.io/semaphoreui/semaphore:v2.14.6
    user: "${UID}:${GID}"
    ports:
      - 3030:3000
    environment:
      - SEMAPHORE_DB_USER=${SEMAPHORE_DB_USER}
      - SEMAPHORE_DB_PASS=${SEMAPHORE_DB_PASS}
      - SEMAPHORE_DB_HOST=${SEMAPHORE_DB_HOST}
      - SEMAPHORE_DB_PORT=${SEMAPHORE_DB_PORT}
      - SEMAPHORE_DB_DIALECT=${SEMAPHORE_DB_DIALECT}
      - SEMAPHORE_DB=${SEMAPHORE_DB}
      - SEMAPHORE_PLAYBOOK_PATH=${SEMAPHORE_PLAYBOOK_PATH}
      - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD}
      - SEMAPHORE_ADMIN_NAME=${SEMAPHORE_ADMIN_NAME}
      - SEMAPHORE_ADMIN_EMAIL=${SEMAPHORE_ADMIN_EMAIL}
      - SEMAPHORE_ADMIN=${SEMAPHORE_ADMIN}
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
      - ANSIBLE_HOST_KEY_CHECKING=${ANSIBLE_HOST_KEY_CHECKING}
    volumes:
      - /DATA/AppData/semaphore/inventory/:/inventory
      - /DATA/AppData/semaphore/authorized-keys/:/authorized-keys
      - /DATA/AppData/semaphore/config/:/etc/semaphore
    restart: unless-stopped
