---
services:
  mysql:
    image: docker.io/library/mysql:9.3
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - /DATA/AppData/mysql/:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    ports:
      - 8082:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    restart: unless-stopped
