---
services:
  npm:
    image: 'jc21/nginx-proxy-manager:2.12.3'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /DATA/AppData/nginx-proxy-manager/data:/data
      - /DATA/AppData/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
