---
services:
  vaultwarden:
    image: 'vaultwarden/server:1.33.2'
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - '10380:80'
    volumes:
      - /DATA/AppData/vaultwarden/data:/data
    environment:
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
